default_install_hook_types:
  - pre-commit
  - prepare-commit-msg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '^.*\.(bin|exe|jpg|png|gif|md)$'
      - id: check-yaml
      - id: check-json

  - repo: local
    hooks:
    -   id: gen_ai_commit_message
        name: AI Commit Message
        description: Generate commit message using AI
        entry: gen_ai_commit_message
        language: python
        args: [--openai_key, 'sk-proj-pPkf0GH5LzbVFno8Eyc1T3BlbkFJY628EJOBgGN6wNMN494j']

