-   id: gen_ai_commit_message
    name: AI Commit Message
    description: Generate commit message using AI
    entry: gen_ai_commit_message
    language: python
    # language_version: python3.9
    always_run: true
    stages: [prepare-commit-msg]
